### ISSUE TITLE
org.neo4j.ogm.database configuration is not working

### ISSUE THREAD

**Issue by dicksonprof** [neo4j/neo4j-ogm-quarkus#130]
Tried to connect the configured database but it always connects to default.

in BoltDriver, this value is always null, thus sessions always connecting to default

 if (this.database != null) {
                sessionConfigBuilder = sessionConfigBuilder.withDatabase(database);
            }

 @Override
    public void configure(Configuration newConfiguration) {

        close();

        super.configure(newConfiguration);

        this.driverConfig = buildDriverConfig();
        this.credentials = this.configuration.getCredentials();
        this.database = this.configuration.getDatabase();
        this.databaseSelectionProvider = this.configuration.getDatabaseSelectionProvider();
        this.userSelectionProvider = this.configuration.getUserSelectionProvider();

        if (this.configuration.getVerifyConnection()) {
            checkDriverInitialized();
        }
    }

Cant call this as well as this is using the recorded value.

**Comment by michael-simons** [comment]
Thanks for using our integration.

We offer `org.neo4j.ogm.database` as configurational property for this exact purpose.
