### ISSUE TITLE
Add a optional packages property for packages to scan for sessionfactory

### ISSUE THREAD

**Issue by dicksonprof** [neo4j/neo4j-ogm-quarkus#131]
var sessionFactoryRuntimeValue = recorder
			.initializeSessionFactory(driverBuildItem.getValue(), shutdownContext, ogmProperties, allPackages);

In Neo4jOgmProcessor currently scans all packages.
I could not get it work and i started to add lots of dependencies so that i can compile.

 // Neo4j scan packages missing dependency
    implementation("org.conscrypt:conscrypt-openjdk:2.5.2:osx-x86_64")
    implementation("com.github.luben:zstd-jni:1.5.2-5")

    testImplementation("org.codehaus.jettison:jettison:1.5.3")
    testImplementation("io.mockk:mockk-agent-jvm:1.13.2")
    // https://mvnrepository.com/artifact/nu.xom/com.springsource.nu.xom
    testImplementation("nu.xom:com.springsource.nu.xom:1.2.5")
    // https://mvnrepository.com/artifact/org.osgi/org.osgi.framework
    testImplementation("org.osgi:org.osgi.framework:1.10.0")
    // https://mvnrepository.com/artifact/org.osgi/org.osgi.dto
    testImplementation("org.osgi:org.osgi.dto:1.1.1")
    // https://mvnrepository.com/artifact/io.vertx/vertx-auth-common
    testImplementation("io.vertx:vertx-auth-common:4.3.6")
    // https://mvnrepository.com/artifact/io.vertx/vertx-auth-otp
    testImplementation("io.vertx:vertx-auth-otp:4.3.6")
    // https://mvnrepository.com/artifact/net.java.dev.jna/jna
    testImplementation("net.java.dev.jna:jna:5.13.0")

**Comment by michael-simons** [comment]
We don't bring in those dependencies.

We offer `org.neo4j.ogm.base-packages` as Quarkus configuration property for that exact purpose. See the readme.
