### ISSUE TITLE
Switch db in uri connection 

### ISSUE THREAD

**Issue by FrancescoCoco** [neo4j/neo4j-ogm-quarkus#229]
Hi everybody, 
 I'm opening this issue because I'm not able to switch the neo4j db that I use in the uri string. 
Infact the session is opened towards the default neo4j db. 
I'm using these dependencies: 

    **<dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-ogm-quarkus</artifactId>
        <version>3.3.1</version>
    </dependency>**

    <**dependency>
        <groupId>eu.michael-simons.neo4j</groupId>
        <artifactId>neo4j-migrations-quarkus</artifactId>
        <version>2.5.3</version>
    </dependency>**
    
quarkus.neo4j.uri=bolt://localhost:7681/name_db
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=password

**Comment by michael-simons** [comment]
Hej @FrancescoCoco Thanks for using our stuff.

So the underlying project here [quarkus-neo4j](https://github.com/quarkiverse/quarkus-neo4j) does only provide the driver connected to a dbms (instance or cluster). The driver is unaware of the database at this point.

To configure the OGM session to use your specific database, do this in _this_ project, via the dedicated property:

```
org.neo4j.ogm.database
```

The same goes for [neo4j-migrations](https://github.com/michael-simons/neo4j-migrations)

```
org.neo4j.migrations.database
```

In that project you can even configure not only one, but two databases, in case you want to store the migration graph independent from your graph, via

```
org.neo4j.migrations.schema-database
```

Please let us know if this helps. Thanks.

**Comment by FrancescoCoco** [comment]
Hi @michael-simons thanks for the answer. 
Your suggestion help me to resolve my problem. 
It was also necessary for me to change the version of neo4j I was using.
Thank you
Francesco

**Comment by FrancescoCoco** [comment]
Hi @michael-simons. 
I don't know why, to select a specific database for migrations 
`org.neo4j.migrations.database` 
This above code is working. 
If I need to select a specific database to write or read data I insert in the application.properties file your suggestion: 
`org.neo4j.ogm.database` 
But it doesn't work and it still chooses the default db. 
Please let me know if you have any idea about this behavior.

**Comment by michael-simons** [comment]
It's a bug, a 3.3.2 release will go out soon.

**Comment by michael-simons** [comment]
Thank you for reporting this 🙇
